name: Build

# Verifies that the app compiles.

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: "Build app"
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout PR branch"
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: "Set up Android SDK"
        uses: android-actions/setup-android@v3

      - name: "Set up Android NDK"
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c

      - name: "Build app"
        run: ./kotlin build
